const PSETS={
  mate2:{name:'Mate en 1',icon:'♛',diff:'easy',diffLabel:'Fácil',desc:'8 puzzles',points:100,category:'MATE',
    puzzles:[
      {fen:'r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',solution:['h5f7'],concept:'Mate del Pastor',desc:'La Dama en h5 mata en f7. ¡El clásico mate del pastor!',points:100},
      {fen:'6k1/5ppp/8/8/8/8/5PPP/4RK2 w - - 0 1',solution:['e1e8'],concept:'Torre al octavo',desc:'La torre domina la octava fila. Un solo golpe decide la partida.',points:100},
      {fen:'k7/8/KQ6/8/8/8/8/8 w - - 0 1',solution:['b6b7'],concept:'Mate de Dama',desc:'La dama y el rey acorralan al rey rival en el borde.',points:100},
      {fen:'4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',solution:['e1e8'],concept:'Torres dobladas',desc:'Las torres dobladas en columna abierta son devastadoras.',points:100},
      {fen:'6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',solution:['e1e8'],concept:'Torre en la 8ª',desc:'La torre en la octava fila corta toda escapatoria al rey.',points:100},
      {fen:'3k4/2ppp3/8/8/8/8/6PP/R5K1 w - - 0 1',solution:['a1a8'],concept:'Jaque de Torre',desc:'La torre corta todas las casillas de escape del rey negro.',points:100},
      {fen:'6k1/5ppp/8/8/3Q4/8/6PP/6K1 w - - 0 1',solution:['d4d8'],concept:'Dama activa',desc:'La dama centralizada domina el tablero.',points:100},
      {fen:'7k/R7/8/8/8/8/8/1R2K3 w - - 0 1',solution:['b1b8'],concept:'Ataque coordinado',desc:'Torre y rey trabajando juntos crean amenazas irresistibles.',points:100},
    ]},
  forks:{name:'Horquillas',icon:'♞',diff:'med',diffLabel:'Medio',desc:'8 puzzles',points:150,category:'TÁCTICA',
    puzzles:[
      {fen:'r1bqkbnr/ppp2ppp/2np4/4N3/2B1P3/8/PPPP1PPP/R1BQK1NR w KQkq - 0 5',solution:['e5f7'],concept:'Horquilla de Caballo',desc:'El caballo captura en f7 atacando la dama y la torre a la vez.',points:150},
      {fen:'5k1r/8/8/4N3/8/8/8/4K3 w - - 0 1',solution:['e5g6'],concept:'Caballo Central',desc:'El caballo salta a g6 dando jaque y atacando la torre a la vez.',points:150},
      {fen:'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',solution:['d5c7'],concept:'Horquilla Real',desc:'El caballo ataca al rey y a la torre al mismo tiempo.',points:150},
      {fen:'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',solution:['f3e5'],concept:'Control del Centro',desc:'El caballo en e5 ataca dos piezas negras a la vez.',points:150},
      {fen:'r1r2k2/8/8/3N4/8/8/8/4K3 w - - 0 1',solution:['d5b6'],concept:'Acoso al Rey',desc:'El caballo salta a b6 atacando las dos torres negras a la vez.',points:150},
      {fen:'3q4/6k1/8/2N5/8/8/8/4K3 w - - 0 1',solution:['c5e6'],concept:'Bifurcación',desc:'El caballo salta a e6 dando jaque y atacando la dama a la vez.',points:150},
      {fen:'r1b1kb1r/ppppqppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 2 6',solution:['f3g5'],concept:'Caballo Agresivo',desc:'El caballo salta amenazando crear problemas tácticos.',points:150},
      {fen:'r1b2k2/8/8/3N4/8/8/8/4K3 w - - 0 1',solution:['d5b6'],concept:'Posición Ganadora',desc:'El caballo salta a b6 atacando la torre y el alfil a la vez.',points:150},
    ]},
  endgame:{name:'Finales',icon:'♚',diff:'hard',diffLabel:'Difícil',desc:'6 puzzles',points:200,category:'FINAL',
    puzzles:[
      {fen:'8/4k3/8/4K3/3P4/8/8/8 w - - 0 1',solution:['e5d5'],concept:'Oposición de Reyes',desc:'La oposición directa es la clave en finales de peones.',points:200},
      {fen:'8/3k4/8/8/8/3K4/3P4/8 w - - 0 1',solution:['d3d4'],concept:'Rey Activo',desc:'Antes de escoltar al peón, el rey debe avanzar y ganar terreno.',points:200},
      {fen:'8/8/1k6/8/8/8/1K1P4/8 w - - 0 1',solution:['b2c3'],concept:'Escolta del Peón',desc:'El rey escolta al peón pasado hacia la coronación.',points:200},
      {fen:'8/8/8/2k5/3P4/2K5/8/8 w - - 0 1',solution:['c3d3'],concept:'Avance Decisivo',desc:'El rey apoya al peón antes de que pueda avanzar con seguridad.',points:200},
      {fen:'8/8/8/8/6k1/6p1/6K1/8 w - - 0 1',solution:['g2h1'],concept:'Tablas Estratégicas',desc:'A veces las tablas son el mejor resultado disponible.',points:200},
      {fen:'8/8/8/3k4/8/8/4K3/R7 w - - 0 1',solution:['a1a5'],concept:'Torre y Rey',desc:'La torre da jaque en la fila del rey rival, forzándolo a retroceder.',points:200},
    ]},
  opening:{name:'Trampas de apertura',icon:'♟',diff:'easy',diffLabel:'Fácil',desc:'6 puzzles',points:80,category:'APERTURA',
    puzzles:[
      {fen:'r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',solution:['h5f7'],concept:'Mate del Pastor',desc:'Qxf7# es mate. La dama en h5 y el alfil en c4 dominan f7.',points:80},
      {fen:'rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2',solution:['d8h4'],concept:'Jaque Temprano',desc:'La dama sale temprano para dar jaque aprovechando la debilidad.',points:80},
      {fen:'rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/8/PPPP1PPP/RNBQK1NR w KQkq - 2 3',solution:['c4f7'],concept:'Sacrificio en f7',desc:'El alfil sacrifica en f7, el punto más débil del enroque negro.',points:80},
      {fen:'rnbqkbnr/ppp2ppp/8/3pp3/4P3/3P4/PPP2PPP/RNBQKBNR w KQkq - 0 3',solution:['d1h5'],concept:'Ataque con Dama',desc:'La dama sale para presionar f7 y e5 simultáneamente.',points:80},
      {fen:'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',solution:['f1b5'],concept:'Apertura Española',desc:'Ab5 presiona al caballo que defiende e5.',points:80},
      {fen:'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2',solution:['g8f6'],concept:'Desarrollo Natural',desc:'Cf6 desarrolla y ataca e4 al mismo tiempo.',points:80},
    ]},
};
